// packages/dockview-react/src/workbench/workbench.tsx
import {
    type DockviewComponentOptions,
    type GridviewApi,
    type GridviewPanelApi,
    type IDockviewPanelProps,
    type SideBarPosition,
    type WorkbenchActivityBarOptions,
    type WorkbenchApi,
    type WorkbenchBandOptions,
    type WorkbenchPanelOptions,
    type WorkbenchSideBarOptions,
    createWorkbench,
} from 'dockview';
import React from 'react';
import { ReactPanelContentPart } from '../dockview/reactContentPart';
import { ReactGridPanelView } from '../gridview/view';
import { usePortalsLifecycle } from '../react';
import type { PanelParameters } from '../types';

export interface WorkbenchReadyEvent {
    api: WorkbenchApi;
}

/**
 * Props for a chrome-band / side-bar / tool-panel React component. These render
 * as panels in the workbench's outer gridview, so they receive a
 * {@link GridviewPanelApi} and the outer grid's {@link GridviewApi}.
 */
export interface IWorkbenchPanelProps<T extends { [index: string]: any } = any>
    extends PanelParameters<T> {
    api: GridviewPanelApi;
    containerApi: GridviewApi;
}

export interface IWorkbenchReactProps {
    onReady: (event: WorkbenchReadyEvent) => void;
    /**
     * Components for the chrome bands, side bars and tool panel (header,
     * toolbar, status bar, activity bar, primary/secondary side bars, panel).
     */
    components: Record<string, React.FunctionComponent<IWorkbenchPanelProps>>;
    /** Components for the editor area (rendered inside the embedded dockview). */
    editorComponents: Record<
        string,
        React.FunctionComponent<IDockviewPanelProps>
    >;
    /** Extra dockview options for the editor (theme, dnd, etc.). */
    editorProps?: Omit<DockviewComponentOptions, 'createComponent'>;

    header?: WorkbenchBandOptions;
    toolbar?: WorkbenchBandOptions;
    statusBar?: WorkbenchBandOptions;
    activityBar?: WorkbenchActivityBarOptions;
    primarySideBar?: WorkbenchSideBarOptions;
    secondarySideBar?: WorkbenchSideBarOptions;
    panel?: WorkbenchPanelOptions;
    primarySideBarPosition?: SideBarPosition;
    activeViewContainer?: string;
    className?: string;
}

export const WorkbenchReact = React.forwardRef(
    (props: IWorkbenchReactProps, ref: React.ForwardedRef<HTMLDivElement>) => {
        const domRef = React.useRef<HTMLDivElement>(null);
        const workbenchRef = React.useRef<WorkbenchApi | undefined>(undefined);
        const [portals, addPortal] = usePortalsLifecycle();

        React.useImperativeHandle(ref, () => domRef.current!, []);

        // Keep the latest component maps available to the (stable) factories so
        // that swapping a component definition takes effect on the next render
        // without tearing down the workbench.
        const latest = React.useRef(props);
        latest.current = props;

        React.useEffect(() => {
            if (!domRef.current) {
                return () => {
                    // noop
                };
            }

            const api = createWorkbench(domRef.current, {
                header: props.header,
                toolbar: props.toolbar,
                statusBar: props.statusBar,
                activityBar: props.activityBar,
                primarySideBar: props.primarySideBar,
                secondarySideBar: props.secondarySideBar,
                panel: props.panel,
                primarySideBarPosition: props.primarySideBarPosition,
                activeViewContainer: props.activeViewContainer,
                className: props.className,
                createComponent: (options) =>
                    new ReactGridPanelView(
                        options.id,
                        options.name,
                        latest.current.components[options.name],
                        { addPortal }
                    ),
                dockview: {
                    ...(props.editorProps ?? {}),
                    createComponent: (options) =>
                        new ReactPanelContentPart(
                            options.id,
                            latest.current.editorComponents[options.name],
                            { addPortal }
                        ),
                },
            });

            const { clientWidth, clientHeight } = domRef.current;
            api.layout(clientWidth, clientHeight);

            props.onReady?.({ api });

            workbenchRef.current = api;

            return () => {
                workbenchRef.current = undefined;
                api.dispose();
            };
        }, []);

        return (
            <div style={{ height: '100%', width: '100%' }} ref={domRef}>
                {portals}
            </div>
        );
    }
);
WorkbenchReact.displayName = 'WorkbenchComponent';

// packages/dockview-angular/src/lib/workbench/workbench-angular.component.ts
import {
    ChangeDetectionStrategy,
    Component,
    ElementRef,
    EnvironmentInjector,
    EventEmitter,
    inject,
    Injector,
    Input,
    type OnDestroy,
    type OnInit,
    Output,
    type TemplateRef,
    type Type,
    ViewChild,
} from '@angular/core';
import {
    createWorkbench,
    type SideBarPosition,
    type WorkbenchActivityBarOptions,
    type WorkbenchApi,
    type WorkbenchBandOptions,
    type WorkbenchComponentOptions,
    type WorkbenchPanelOptions,
    type WorkbenchSideBarOptions,
} from 'dockview';
import { AngularFrameworkComponentFactory } from '../utils/component-factory';
import type { WorkbenchAngularReadyEvent } from './types';

@Component({
    selector: 'dv-workbench',
    standalone: true,
    template: '<div #workbenchContainer class="workbench-container"></div>',
    styles: [
        `
            :host {
                display: block;
                width: 100%;
                height: 100%;
            }

            .workbench-container {
                width: 100%;
                height: 100%;
            }
        `,
    ],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WorkbenchAngularComponent implements OnInit, OnDestroy {
    @ViewChild('workbenchContainer', { static: true })
    private readonly containerRef!: ElementRef<HTMLDivElement>;

    /** Components for the chrome bands, side bars and tool panel. */
    @Input() components!: Record<string, Type<any> | TemplateRef<any>>;
    /** Components for the editor area (embedded dockview). */
    @Input() editorComponents!: Record<string, Type<any> | TemplateRef<any>>;
    @Input() editorProps?: WorkbenchComponentOptions['dockview'];

    @Input() header?: WorkbenchBandOptions;
    @Input() toolbar?: WorkbenchBandOptions;
    @Input() statusBar?: WorkbenchBandOptions;
    @Input() activityBar?: WorkbenchActivityBarOptions;
    @Input() primarySideBar?: WorkbenchSideBarOptions;
    @Input() secondarySideBar?: WorkbenchSideBarOptions;
    @Input() panel?: WorkbenchPanelOptions;
    @Input() primarySideBarPosition?: SideBarPosition;
    @Input() activeViewContainer?: string;
    @Input() className?: string;

    @Output() ready = new EventEmitter<WorkbenchAngularReadyEvent>();

    private workbenchApi?: WorkbenchApi;
    private readonly injector = inject(Injector);
    private readonly environmentInjector = inject(EnvironmentInjector);

    ngOnInit(): void {
        if (!this.components) {
            throw new Error(
                'WorkbenchAngularComponent: components input is required'
            );
        }
        if (!this.editorComponents) {
            throw new Error(
                'WorkbenchAngularComponent: editorComponents input is required'
            );
        }

        // The chrome bands are gridview panels; the editor panels are dockview
        // content renderers. Each set resolves through its own factory.
        const bandFactory = new AngularFrameworkComponentFactory(
            this.components,
            this.injector,
            this.environmentInjector
        );
        const editorFactory = new AngularFrameworkComponentFactory(
            this.editorComponents,
            this.injector,
            this.environmentInjector
        );

        this.workbenchApi = createWorkbench(this.containerRef.nativeElement, {
            header: this.header,
            toolbar: this.toolbar,
            statusBar: this.statusBar,
            activityBar: this.activityBar,
            primarySideBar: this.primarySideBar,
            secondarySideBar: this.secondarySideBar,
            panel: this.panel,
            primarySideBarPosition: this.primarySideBarPosition,
            activeViewContainer: this.activeViewContainer,
            className: this.className,
            createComponent: (options) =>
                bandFactory.createGridviewComponent(options),
            dockview: {
                ...(this.editorProps ?? {}),
                createComponent: (options) =>
                    editorFactory.createDockviewComponent(options),
            },
        });

        const { clientWidth, clientHeight } = this.containerRef.nativeElement;
        this.workbenchApi.layout(clientWidth, clientHeight);

        this.ready.emit({ api: this.workbenchApi });
    }

    ngOnDestroy(): void {
        this.workbenchApi?.dispose();
    }

    getWorkbenchApi(): WorkbenchApi | undefined {
        return this.workbenchApi;
    }
}
